import duckdb
import logging
import os
from decimal import Decimal
from typing import List, Tuple, Any

# Configure standard logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Pipeline Constants
DB_PATH = "data/pokemon_dw.duckdb"
REPORT_DIR = "data/reports"
REPORT_FILE = "analytics_report.md"

def generate_markdown_table(columns: List[str], rows: List[Tuple[Any, ...]]) -> str:
    """
    Generates a Markdown-formatted table from column names and row data.
    """
    if not columns or not rows:
        return "_No data available._\n"

    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join(["---"] * len(columns)) + " |"
    table = [header, separator]

    for row in rows:
        clean_row = []
        for item in row:
            # Safely stringify database results, ensuring consistent float/decimal precision
            if item is None:
                clean_row.append("NULL")
            elif isinstance(item, (float, Decimal)):
                clean_row.append(f"{float(item):.2f}")
            else:
                clean_row.append(str(item))

        table.append("| " + " | ".join(clean_row) + " |")

    return "\n".join(table)

def execute_query(con: duckdb.DuckDBPyConnection, query: str) -> Tuple[List[str], List[Tuple[Any, ...]]]:
    """
    Executes a SQL query and returns column names and fetched rows.
    """
    con.execute(query)
    columns = [desc[0] for desc in con.description]
    rows = con.fetchall()
    return columns, rows

def run_analysis():
    """
    Main execution block for generating the analytics report.
    """
    logger.info("Initializing analytics reporting pipeline...")

    os.makedirs(REPORT_DIR, exist_ok=True)
    report_path = os.path.join(REPORT_DIR, REPORT_FILE)

    # Define the analytical queries logically to keep the execution flow clean
    queries = [
        {
            "title": "Highest Average Attack Stat by Primary Type",
            "description": "Identifies the Pokémon type with the highest average base attack stat.",
            "sql": """
                SELECT
                    type_name AS "Type",
                    total_pokemon AS "Total Pokemon",
                    avg_attack AS "Average Attack"
                FROM marts.agg_type_stats
                ORDER BY avg_attack DESC
                LIMIT 1
            """
        },
        {
            "title": "Top 5 Heaviest Pokémon",
            "description": "Lists the five heaviest Pokémon along with their primary elemental type.",
            "sql": """
                SELECT
                    p.pokemon_name AS "Pokemon",
                    p.weight AS "Weight (hectograms)",
                    b.type_name AS "Primary Type"
                FROM marts.dim_pokemon p
                JOIN marts.bridge_pokemon_type b
                    ON p.pokemon_id = b.pokemon_id
                    AND b.is_primary = true
                ORDER BY p.weight DESC
                LIMIT 5
            """
        },
        {
            "title": "Attack-to-Defense Ratio Analysis",
            "description": "Calculates the ratio of Base Attack to Base Defense for Pokémon with a minimum of 100 Base Attack.",
            "sql": """
                SELECT
                    p.pokemon_name AS "Pokemon",
                    b.type_name AS "Primary Type",
                    f.stat_attack AS "Attack",
                    f.stat_defense AS "Defense",
                    ROUND(f.stat_attack * 1.0 / NULLIF(f.stat_defense, 0), 2) AS "Attack/Defense Ratio"
                FROM marts.dim_pokemon p
                JOIN marts.fact_pokemon_stats f
                    ON p.pokemon_id = f.pokemon_id
                JOIN marts.bridge_pokemon_type b
                    ON p.pokemon_id = b.pokemon_id
                    AND b.is_primary = true
                WHERE f.stat_attack > 100
                ORDER BY "Attack/Defense Ratio" DESC
                LIMIT 5
            """
        }
    ]

    try:
        con = duckdb.connect(DB_PATH)
        logger.info("Successfully connected to the Data Warehouse.")

        # Generate the Markdown artifact
        with open(report_path, "w", encoding="utf-8") as f:
            f.write("# Data Warehouse Analytics Report\n\n")
            f.write("> *Automated analytical report generated by the data pipeline.*\n\n")

            for idx, item in enumerate(queries, 1):
                logger.info(f"Executing query {idx}/{len(queries)}: {item['title']}")
                cols, rows = execute_query(con, item["sql"])

                f.write(f"### {idx}. {item['title']}\n")
                f.write(f"*{item['description']}*\n\n")
                f.write(generate_markdown_table(cols, rows) + "\n\n")

        logger.info("Analytics pipeline completed successfully.")
        logger.info(f"Report generated and saved to: {report_path}")

    except Exception as e:
        logger.error(f"Failed to generate analytics report: {e}")
        raise
    finally:
        if 'con' in locals():
            con.close()

if __name__ == "__main__":
    run_analysis()
